### PR TITLE
Improvement Report

### PR DESCRIPTION
**Pull request by ahmadridhoramadhan**
## before
Screenshot from 2024-08-21 14-54-47

## after
image

### CODE REVIEW

**Comment by ahmadridhoramadhan** [comment]
## fix
- add date to failed log
- colored some message
image

**Comment by ahmadridhoramadhan** [comment]
format date changed
image

**Comment by ahmadridhoramadhan** [comment]
change color 
Screenshot from 2024-08-24 10-20-31

**Comment by thisnugroho** [comment]
bisa di review juga pak @navotera

**Comment by ahmadridhoramadhan** [comment]
fixed
image

**Review by navotera — APPROVED** [review]

**Pull request merged**
